spring:
  application:
    name: spring-cloud-ribbon
 
server:
  port: 8080
 
ping-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8082,localhost:8081,localhost:8083
    ServerListRefreshInterval: 15000